# Generated by Django 5.2.3 on 2025-07-19 18:27

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('letter', models.CharField(max_length=1)),
                ('category', models.CharField(default='Abu Dhabi', max_length=100)),
                ('category_en', models.CharField(blank=True, max_length=100, verbose_name='Category (EN)')),
                ('category_slug', models.SlugField(blank=True, max_length=100, verbose_name='Category slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_info', models.TextField(blank=True, verbose_name='Location')),
                ('how_to_get', models.TextField(blank=True, verbose_name='How to get there')),
                ('travel_tips', models.TextField(blank=True, verbose_name='Useful tips')),
                ('location_map_embed', models.TextField(blank=True, verbose_name='Map embed (iframe from Google Maps)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/')),
                ('orientation', models.CharField(blank=True, choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.article')),
            ],
        ),
    ]
